# Generated by Django 2.2.1 on 2019-05-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCardPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ratio', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbin.Card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbin.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='cards',
            field=models.ManyToManyField(through='futbin.PlayerCardPrices', to='futbin.Card'),
        ),
    ]
