# Generated by Django 2.2.1 on 2019-08-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
    ]
